// Mocks generated by Mockito 5.4.6 from annotations
// in gym_tracker/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:gym_tracker/models/post_workout_recovery.dart' as _i4;
import 'package:gym_tracker/models/pre_workout.dart' as _i2;
import 'package:gym_tracker/models/user_preferences.dart' as _i3;
import 'package:gym_tracker/models/workout.dart' as _i8;
import 'package:gym_tracker/services/local_storage_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePreWorkout_0 extends _i1.SmartFake implements _i2.PreWorkout {
  _FakePreWorkout_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserPreferences_1 extends _i1.SmartFake
    implements _i3.UserPreferences {
  _FakeUserPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostWorkoutRecovery_2 extends _i1.SmartFake
    implements _i4.PostWorkoutRecovery {
  _FakePostWorkoutRecovery_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i5.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setPrefsForTesting(_i6.SharedPreferences? prefs) => super.noSuchMethod(
    Invocation.method(#setPrefsForTesting, [prefs]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> savePreWorkout(_i2.PreWorkout? preWorkout) =>
      (super.noSuchMethod(
            Invocation.method(#savePreWorkout, [preWorkout]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.PreWorkout> getPreWorkout() =>
      (super.noSuchMethod(
            Invocation.method(#getPreWorkout, []),
            returnValue: _i7.Future<_i2.PreWorkout>.value(
              _FakePreWorkout_0(this, Invocation.method(#getPreWorkout, [])),
            ),
          )
          as _i7.Future<_i2.PreWorkout>);

  @override
  _i7.Future<void> saveUserPreferences(_i3.UserPreferences? prefs) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserPreferences, [prefs]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.UserPreferences> getUserPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getUserPreferences, []),
            returnValue: _i7.Future<_i3.UserPreferences>.value(
              _FakeUserPreferences_1(
                this,
                Invocation.method(#getUserPreferences, []),
              ),
            ),
          )
          as _i7.Future<_i3.UserPreferences>);

  @override
  _i7.Future<void> saveWorkout(_i8.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#saveWorkout, [workout]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.Workout>> getWorkoutHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutHistory, []),
            returnValue: _i7.Future<List<_i8.Workout>>.value(<_i8.Workout>[]),
          )
          as _i7.Future<List<_i8.Workout>>);

  @override
  _i7.Future<void> saveSoreness(_i4.PostWorkoutRecovery? soreness) =>
      (super.noSuchMethod(
            Invocation.method(#saveSoreness, [soreness]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.PostWorkoutRecovery> getSoreness(String? workoutId) =>
      (super.noSuchMethod(
            Invocation.method(#getSoreness, [workoutId]),
            returnValue: _i7.Future<_i4.PostWorkoutRecovery>.value(
              _FakePostWorkoutRecovery_2(
                this,
                Invocation.method(#getSoreness, [workoutId]),
              ),
            ),
          )
          as _i7.Future<_i4.PostWorkoutRecovery>);

  @override
  _i7.Future<void> initializeMockData() =>
      (super.noSuchMethod(
            Invocation.method(#initializeMockData, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
