// Mocks generated by Mockito 5.4.6 from annotations
// in gym_tracker/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:gym_tracker/models/pre_workout.dart' as _i2;
import 'package:gym_tracker/models/user_preferences.dart' as _i3;
import 'package:gym_tracker/models/workout.dart' as _i6;
import 'package:gym_tracker/services/local_storage_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePreWorkout_0 extends _i1.SmartFake implements _i2.PreWorkout {
  _FakePreWorkout_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserPreferences_1 extends _i1.SmartFake
    implements _i3.UserPreferences {
  _FakeUserPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i4.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> setPreferences(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#setPreferences, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<dynamic> getPreferences(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getPreferences, [key]),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<void> saveWorkout(_i6.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#saveWorkout, [workout]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Workout>> getWorkoutHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutHistory, []),
            returnValue: _i5.Future<List<_i6.Workout>>.value(<_i6.Workout>[]),
          )
          as _i5.Future<List<_i6.Workout>>);

  @override
  _i5.Future<void> savePreWorkout(_i2.PreWorkout? preWorkout) =>
      (super.noSuchMethod(
            Invocation.method(#savePreWorkout, [preWorkout]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.PreWorkout> getPreWorkout() =>
      (super.noSuchMethod(
            Invocation.method(#getPreWorkout, []),
            returnValue: _i5.Future<_i2.PreWorkout>.value(
              _FakePreWorkout_0(this, Invocation.method(#getPreWorkout, [])),
            ),
          )
          as _i5.Future<_i2.PreWorkout>);

  @override
  _i5.Future<void> saveUserPreferences(_i3.UserPreferences? prefs) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserPreferences, [prefs]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserPreferences> getUserPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getUserPreferences, []),
            returnValue: _i5.Future<_i3.UserPreferences>.value(
              _FakeUserPreferences_1(
                this,
                Invocation.method(#getUserPreferences, []),
              ),
            ),
          )
          as _i5.Future<_i3.UserPreferences>);

  @override
  _i5.Future<void> clearData() =>
      (super.noSuchMethod(
            Invocation.method(#clearData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> initializeMockData() =>
      (super.noSuchMethod(
            Invocation.method(#initializeMockData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
